### ISSUE TITLE
When going from sgt to SWAT you get two secondary arms.

### ISSUE THREAD

**Issue by coderiekelt** [syl0r/Perpheads-Issues#103]
Was using a Glock as an sergeant, went on SWAT and this happened:
http://steamcommunity.com/sharedfiles/filedetails/?id=424112936

**Comment by Creepis** [comment]
This also happens when just joining the S.W.A.T as a regular police officer, for example having a Glock 20 and then joining the S.W.A.T team will allow you to have a M9 and a Glock 20 in your inventory.Ofcourse, you cannot use the Glock 20, it is just taking up space and weight and if I recall correctly, switching sidearms automatically get's rid of the double sidearm.
