### ISSUE TITLE
Extremely buggy RC

### ISSUE THREAD

**Issue by RogueCarTyres** [syl0r/Perpheads-Issues#187]
RC vehicles are buggy when you attach cars to hooks. They tend to fly away when too close to the RC vehicle.

**Comment by jimmythehamster** [comment]
Despite this being hilarious a fix would save many lives.

**Comment by LaCreepis** [comment]
This regurarly happens when people always attach the hook ontop of the hood or on the side of a car. Just place it under the engine behind the car's back and you should have no problem towing it. And as far as I've heard this problem is occuring more often because of the tow trucks increase in weight change to tow heavier vehicles more easily, don't quote me on this one however.

**Comment by syl0r** [comment]
This is really just a problem with many roadcrews trolling. If you play the job properly that should pretty much never happen.
