### ISSUE TITLE
Randomly DCing

### ISSUE THREAD

**Issue by JoeyLopezLopezFamily** [syl0r/Perpheads-Issues#193]
So I was in the middle of arresting a man for shooting me, when for some reason I just disconnected. My internet was still working and my ping was fine, but for some reason it just kicked me. It didnt give me a kick message either, it just said "The server is full" for some strange reason. Please fix this. I wasnt kicked by an admin either, I hadnt broken any rules in the server at the time.

**Comment by LaCreepis** [comment]
Same with my issue, however this might be because you had another tab open that connects to the server once a player slot is open which caused you to reconnect and awkwardly enough it didn't have another slot for you. Here's the issue I talked about https://github.com/syl0r/Perpheads-Issues/issues/179

**Comment by JoeyLopezLopezFamily** [comment]
How do I close the tab once in the game?

-----Original Message-----

**Comment by syl0r** [comment]
Pretty sure this is caused by steams auto connect function. If you connect manually and forget to turn it off it will reconnect you after some time.
