### ISSUE TITLE
Invisible

### ISSUE THREAD

**Issue by smash123** [syl0r/Perpheads-Issues#238]
When there's a shootout, everything goes invisible. This happens 70% of the time for me.
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)

**Comment by LaCreepis** [comment]
This probably still happens because of too many LUA effects. Gunsmoke, bullet impact effects, etc. However, removing dead bodies somehow helps with this issue which makes it less frequent or just prevents it overall. There is no real fix for this unless we disable impact effects yet again until we find another fix. Also if you stop your demo and decide to record a new one note that it crashes your game as it literally tries it best to refresh the whole map/entities but just fails and closes down Garry's Mod.

**Comment by XxWh1t3WolfxX** [comment]
Best advice I can give is, every few minutes during a raid. Do r_cleardecals into the console, this will remove the blood, gunshots. Usually this helps me.

**Comment by StephenPuffs** [comment]
Duplicate, but also it's partially an error with the Source engine itself.
