### ISSUE TITLE
Shots don't hit the target/wall in one of the "Very Long" range options of the firing range

### ISSUE THREAD

**Issue by LaCreepis** [syl0r/Perpheads-Issues#577]
Your bullets don't travel all the way until the end on the "Very Long" range option on the first one you enter. The one right next to the wall/end works just fine though for some reason.

While we're at the topic of firing range please fix the magazines as you only get 1 magazine for each gun when you choose to use your own ammo tyvm

**Comment by StephenPuffs** [comment]
Works fine for me https://i.imgur.com/hyJ1Gqo.png with some guns, but others did have issues it seems, so that's now addressed but it is a sort of work around and I will need to check if the physical model of how it operates still checks out another time.

Being provided empty mags is fixed additionally.
